#!/usr/bin/env python3
"""Verify that a comment edit touched only comments.

Usage: check_comment_edit.py <file>                 (original = git HEAD version)
       check_comment_edit.py <original> <modified>

Looks only at the changed lines. Each one must be blank, a whole-line comment,
or a code line whose code part is unchanged (a trailing comment was edited).
Also checks that pragmas and ticket/issue references in removed comments
survived, and reports how much comment text was removed.

Exit code 0 = clean, 1 = something needs review, 2 = usage error.
"""

import difflib
import re
import subprocess
import sys
from pathlib import Path

# ext -> (line markers, block (open, close) pairs, docstring delimiters).
# A docstring delimiter opens a comment only when nothing but whitespace or a
# string prefix precedes it on the line; otherwise it is an ordinary string.
C = (["//"], [("/*", "*/")], [])
HASH = (["#"], [], [])
PY = (["#"], [], ['"""', "'''"])
SQL = (["--"], [("/*", "*/")], [])
MARKUP = ([], [("<!--", "-->")], [])
LANGS = {
    ".py": PY, ".pyi": PY,
    ".sh": HASH, ".bash": HASH, ".zsh": HASH, ".yaml": HASH, ".yml": HASH,
    ".toml": HASH, ".tf": HASH, ".rb": HASH, ".pl": HASH, ".r": HASH,
    ".sql": SQL, ".lua": (["--"], [("--[[", "]]")], []),
    ".php": (["//", "#"], [("/*", "*/")], []),
    ".css": ([], [("/*", "*/")], []),
    ".html": MARKUP, ".xml": MARKUP, ".svg": MARKUP,
    ".vue": (["//"], [("/*", "*/"), ("<!--", "-->")], []),
}
for ext in (".js .mjs .cjs .ts .tsx .jsx .go .java .kt .kts .scala .c .h .cc .cpp .hpp "
            ".cs .swift .rs .dart .scss .less .m .mm .groovy .proto .zig").split():
    LANGS[ext] = C
FALLBACK = (["#", "//"], [("/*", "*/")], [])

# Comments that are semantically code, or whose loss is silently expensive.
PRAGMA_RE = re.compile("|".join([
    r"^#!", r"-\*-\s*coding", r"\bcoding[:=]\s*[-\w.]+",
    r"\bnoqa\b", r"\btype:\s*ignore", r"\bpragma:\s*no\s*cover", r"\bpylint:\s*",
    r"\bmypy:\s*", r"\bpyright:\s*", r"\bruff:\s*", r"\bfmt:\s*(on|off|skip)",
    r"\bnosec\b", r"\byapf:\s*", r"\bisort:\s*",
    r"eslint-(disable|enable)", r"@ts-(ignore|expect-error|nocheck)",
    r"prettier-ignore", r"biome-ignore", r"(istanbul|c8|v8)\s+ignore",
    r"webpackChunkName", r"@jsx\b", r"@flow\b",
    r"\bgo:(build|generate|embed|linkname|noinline)\b", r"\+build\b",
    r"\bnolint\b", r"\bIWYU\b", r"clang-format\s+(on|off)",
    r"\brubocop:\s*", r"frozen_string_literal", r"\bshellcheck\s+disable",
    r"@generated\b", r"Code generated by", r"DO\s?NOT\s?EDIT",
    r"SPDX-License-Identifier", r"\bCopyright\b", r"\(c\)\s*\d{4}",
    r"Licensed under", r"\bLicense\b.*\b(MIT|Apache|GPL|BSD|MPL)\b",
]), re.IGNORECASE)

REF_RE = re.compile(
    r"https?://\S+"
    r"|\b(?:CVE-\d{4}-\d+|RFC[-\s]?\d{3,})\b"
    r"|\b[A-Z][A-Z0-9]+-\d+\b"          # JIRA-style key
    r"|(?<![\w/])#\d{2,}\b",             # GitHub-style issue
    re.IGNORECASE,
)
# Upper-case tokens that look like JIRA keys but are not references.
NOT_TICKETS = {
    "UTF", "SHA", "MD", "ISO", "IEEE", "AES", "RSA", "DES", "HMAC", "HTTP", "TLS",
    "SSL", "SSH", "IPV", "IP", "ECDSA", "ED", "X", "GPT", "USB", "PCI", "POSIX",
    "ANSI", "ASCII", "CP", "PBKDF", "CRC", "ECMA", "ES", "WCAG", "NIST", "FIPS",
    "PEP", "IEC", "ISBN", "OAUTH", "TCP", "UDP", "ARM", "ARMV", "AMD", "X86",
    "WIN", "GB", "MB", "KB", "TB", "UUID", "SM", "DNS", "NTP",
}
STR_PREFIXES = {"", "r", "u", "b", "f", "rb", "br", "fr", "rf"}


def split_lines(text: str, lang) -> list:
    """For each line: (code_part, comment_part, opens_docstring), tracking block comments across lines.

    Only quotes, comment markers and block delimiters are recognised, which is
    enough to decide what is comment on the lines a diff touches.
    """
    line_marks, blocks, docs = lang
    openers = [(o, c, False) for o, c in blocks] + [(d, d, True) for d in docs]
    result = []
    block = None      # None | (closer, is_comment)

    for raw in text.splitlines():
        code, com = [], []
        opens_doc = False
        i, n = 0, len(raw)
        while i < n:
            if block:
                closer, is_comment = block
                pos = raw.find(closer, i)
                end = n if pos == -1 else pos + len(closer)
                (com if is_comment else code).append(raw[i:end])
                i = end
                if pos != -1:
                    block = None
                continue
            if any(raw.startswith(m, i) for m in line_marks):
                com.append(raw[i:])
                break
            opened = next(((o, c, d) for o, c, d in openers if raw.startswith(o, i)), None)
            if opened:
                o, closer, is_doc = opened
                is_comment = not is_doc or "".join(code).strip().lower() in STR_PREFIXES
                opens_doc = opens_doc or (is_doc and is_comment)
                pos = raw.find(closer, i + len(o))
                end = n if pos == -1 else pos + len(closer)
                (com if is_comment else code).append(raw[i:end])
                i = end
                if pos == -1:
                    block = (closer, is_comment)
                continue
            ch = raw[i]
            if ch in "\"'`":
                j = i + 1
                while j < n and raw[j] != ch:
                    j += 2 if raw[j] == "\\" else 1
                end = j + 1 if j < n else i + 1      # unterminated: just a quote char
                code.append(raw[i:end])
                i = end
                continue
            code.append(ch)
            i += 1
        # Internal whitespace runs collapse so that removing an inline comment
        # does not register as a code change through the gap it leaves.
        code_part = re.sub(r"(?<=\S)\s+", " ", "".join(code).rstrip())
        result.append((code_part, "".join(com).strip(), opens_doc))
    return result


def refs_in(text: str) -> set:
    found = set()
    for r in REF_RE.findall(text):
        head = r.split("-")[0].upper()
        if head in NOT_TICKETS:
            continue
        found.add(r)
    return found


def check(orig_text: str, mod_text: str, lang, label: str) -> int:
    o_lines, m_lines = split_lines(orig_text, lang), split_lines(mod_text, lang)
    problems = []
    removed_com, added_com, removed_docs, added_docs = [], [], 0, 0

    sm = difflib.SequenceMatcher(None, orig_text.splitlines(), mod_text.splitlines(), autojunk=False)
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            continue
        old, new = o_lines[i1:i2], m_lines[j1:j2]
        old_code = [c for c, _, _ in old if c.strip()]
        new_code = [c for c, _, _ in new if c.strip()]
        if old_code != new_code:
            problems.append(f"Code changed at original lines {i1 + 1}-{i2}, modified lines {j1 + 1}-{j2}:")
            for line in difflib.unified_diff(old_code, new_code, lineterm="", n=0):
                if not line.startswith(("---", "+++", "@@")):
                    problems.append("    " + line)

        old_com = [c for _, c, _ in old if c]
        new_com = [c for _, c, _ in new if c]
        for c in old_com:
            if PRAGMA_RE.search(c) and c not in new_com:
                problems.append(f"Pragma or header lost or altered: {c[:100]}")
        removed_com += old_com
        added_com += new_com
        removed_docs += sum(1 for _, _, d in old if d)
        added_docs += sum(1 for _, _, d in new if d)

    for r in sorted(refs_in("\n".join(removed_com))):
        if r not in mod_text:
            problems.append(f"Reference dropped: {r}")

    print(label)
    o_chars, m_chars = sum(map(len, removed_com)), sum(map(len, added_com))
    print(f"  Comment lines touched: {len(removed_com)} removed, {len(added_com)} added "
          f"({o_chars} -> {m_chars} chars)")
    if m_chars > o_chars:
        print("  Comment text grew. Fine for an under-commented file; check it was not verbosity.")
    if added_docs < removed_docs:
        print(f"  Docstrings removed: {removed_docs - added_docs}. A docstring is runtime data "
              "(help(), doctest, framework-generated docs); confirm removal was intended.")
    if problems:
        print("\nFAIL")
        for p in problems:
            print(f"  {p}")
        return 1
    print("  Code unchanged, pragmas and refs intact.\n\nOK")
    return 0


def git_original(path: Path) -> str:
    try:
        top = subprocess.run(["git", "rev-parse", "--show-toplevel"], cwd=path.parent,
                             capture_output=True, text=True, check=True).stdout.strip()
        rel = path.resolve().relative_to(Path(top).resolve()).as_posix()
        return subprocess.run(["git", "show", f"HEAD:{rel}"], cwd=top,
                              capture_output=True, text=True, check=True).stdout
    except (subprocess.CalledProcessError, ValueError, FileNotFoundError) as e:
        detail = (getattr(e, "stderr", "") or str(e)).strip().splitlines()[0]
        print(f"Cannot read {path} from git HEAD ({detail}).\n"
              "Pass the original file explicitly: check_comment_edit.py <original> <modified>")
        raise SystemExit(2)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def main() -> int:
    args = [Path(a) for a in sys.argv[1:]]
    if len(args) not in (1, 2):
        print(__doc__.strip())
        return 2
    for p in args:
        if not p.is_file():
            print(f"No such file: {p}")
            return 2
    mod = args[-1]
    lang = LANGS.get(mod.suffix.lower(), FALLBACK)
    if len(args) == 2:
        return check(read(args[0]), read(mod), lang, f"{args[0]} -> {mod}")
    return check(git_original(mod), read(mod), lang, f"HEAD:{mod} -> {mod}")


if __name__ == "__main__":
    sys.exit(main())
